DROP TABLE "TB_MEMBER";

CREATE TABLE "TB_MEMBER" (
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
	"BIRTH"	VARCHAR(8)		NOT NULL,
	"PASSWORD"	VARCHAR(500)		NOT NULL,
	"DEPARTMENT"	VARCHAR(50)		NOT NULL,
	"POSITION"	VARCHAR(30)		NOT NULL,
	"EMAIL_KEY"	VARCHAR2(200)		NOT NULL,
	"EMAIL_VERIFY_PNTTM"	DATE		NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"LAST_UPDUSR_ID"	VARCHAR2(20)		NOT NULL,
	"QUIT_AT"	CHAR(1)	DEFAULT N	NOT NULL
);

DROP TABLE "TB_BOARD";

CREATE TABLE "TB_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"NUM"	NUMBER		NOT NULL,
	"NOTICE_AT"	CHAR(1)	DEFAULT N	NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"BOARD_VIEW"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DATE"	DATE		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"LAST_UPDUSR_ID"	VARCHAR2(20)		NOT NULL,
	"DELE_AT"	CHAR(1)	DEFAULT N	NOT NULL
);

DROP TABLE "TB_CATEGORY";

CREATE TABLE "TB_CATEGORY" (
	"NUM"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(50)		NOT NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"LAST_UPDUSR_ID"	VARCHAR2(20)		NOT NULL,
	"DELE_AT"	CHAR(1)	DEFAULT N	NOT NULL
);

DROP TABLE "TB_CATEGORE_USER";

CREATE TABLE "TB_CATEGORE_USER" (
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"NUM"	NUMBER		NOT NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"LAST_UPDUSR_ID"	VARCHAR2(20)		NOT NULL,
	"DELE_AT"	CHAR(1)	DEFAULT N	NOT NULL
);

DROP TABLE "TB_ATTENDANCE";

CREATE TABLE "TB_ATTENDANCE" (
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"DAY"	VARCHAR2(20)		NOT NULL,
	"IN_TIME"	VARCHAR2(20)		NOT NULL,
	"OUT_TIME"	VARCHAR2(20)		NOT NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"LATENESS_AT"	CHAR(1)	DEFAULT N	NOT NULL,
	"LATENESS_REASON"	VARCHAR2(50)		NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"LAST_UPDUSR_ID"	VARCHAR2(20)		NOT NULL,
	"DELE_AT"	CHAR(1)	DEFAULT N	NOT NULL
);

DROP TABLE "TB_CHAT_ROOM";

CREATE TABLE "TB_CHAT_ROOM" (
	"CHAT_ROOM_NUMBER"	NUMBER		NOT NULL,
	"CHAT_ROOM_TITLE"	VARCHAR2(50)		NOT NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"DELE_AT"	CHAR(1)	DEFAULT N	NOT NULL
);

DROP TABLE "TB_CHAR_USER";

CREATE TABLE "TB_CHAR_USER" (
	"CHAT_ROOM_NUMBER"	NUMBER		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"DELE_AT"	CHAR(1)		NOT NULL
);

DROP TABLE "TB_COMMON_CODE";

CREATE TABLE "TB_COMMON_CODE" (
	"CODE"	VARCHAR2(50)		NOT NULL,
	"CODE_NAME"	VARCHAR2(50)		NOT NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"LAST_UPDUSR_ID"	VARCHAR2(20)		NOT NULL,
	"USE_AT"	CHAR(1)		NOT NULL
);

DROP TABLE "TB_COMMON_CODE_DETAIL";

CREATE TABLE "TB_COMMON_CODE_DETAIL" (
	"DETAIL_CODE"	VARCHAR2(50)		NOT NULL,
	"CODE"	VARCHAR2(50)		NOT NULL,
	"DETAIL_CODE_NAME"	VARCHAR2(50)		NOT NULL,
	"FRST_REGIST_PNTTM"	DATE		NOT NULL,
	"FRST_REGISTER_ID"	VARCHAR(20)		NOT NULL,
	"LAST_UPDT_PNTTM"	DATE		NOT NULL,
	"LAST_UPDUSR_ID"	VARCHAR2(20)		NOT NULL,
	"USE_AT"	CHAR(1)		NOT NULL
);

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_TB_MEMBER" PRIMARY KEY (
	"EMAIL"
);

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "PK_TB_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "TB_CATEGORY" ADD CONSTRAINT "PK_TB_CATEGORY" PRIMARY KEY (
	"NUM"
);

ALTER TABLE "TB_CHAT_ROOM" ADD CONSTRAINT "PK_TB_CHAT_ROOM" PRIMARY KEY (
	"CHAT_ROOM_NUMBER"
);

ALTER TABLE "TB_COMMON_CODE" ADD CONSTRAINT "PK_TB_COMMON_CODE" PRIMARY KEY (
	"CODE"
);

ALTER TABLE "TB_COMMON_CODE_DETAIL" ADD CONSTRAINT "PK_TB_COMMON_CODE_DETAIL" PRIMARY KEY (
	"DETAIL_CODE"
);

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "FK_TB_CATEGORY_TO_TB_BOARD_1" FOREIGN KEY (
	"NUM"
)
REFERENCES "TB_CATEGORY" (
	"NUM"
);

ALTER TABLE "TB_CATEGORE_USER" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_CATEGORE_USER_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "TB_MEMBER" (
	"EMAIL"
);

ALTER TABLE "TB_CATEGORE_USER" ADD CONSTRAINT "FK_TB_CATEGORY_TO_TB_CATEGORE_USER_1" FOREIGN KEY (
	"NUM"
)
REFERENCES "TB_CATEGORY" (
	"NUM"
);

ALTER TABLE "TB_ATTENDANCE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_ATTENDANCE_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "TB_MEMBER" (
	"EMAIL"
);

ALTER TABLE "TB_CHAR_USER" ADD CONSTRAINT "FK_TB_CHAT_ROOM_TO_TB_CHAR_USER_1" FOREIGN KEY (
	"CHAT_ROOM_NUMBER"
)
REFERENCES "TB_CHAT_ROOM" (
	"CHAT_ROOM_NUMBER"
);

ALTER TABLE "TB_CHAR_USER" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_CHAR_USER_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "TB_MEMBER" (
	"EMAIL"
);

ALTER TABLE "TB_COMMON_CODE_DETAIL" ADD CONSTRAINT "FK_TB_COMMON_CODE_TO_TB_COMMON_CODE_DETAIL_1" FOREIGN KEY (
	"CODE"
)
REFERENCES "TB_COMMON_CODE" (
	"CODE"
);

